---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - windows_logrotate_test::default
    attributes:
      windows_logrotate_test:
        username: vagrant
        password: vagrant
